[package]
name = "mud"
version = "0.0.0"
description = "A community sourced mod management framework and application"
authors = ["https://github.com/nickheyer"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2.3.2"
dirs = "*"


[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
